# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description:
  All-in-One Property Management System (PMS) focused on medium-sizeations.
repo_name: Property Management System
repo_slug: pms
travis_apt_packages: []
travis_apt_sources: []
