from odoo import fields, models


class PmsIneTourismCategory(models.Model):
    _name = "pms.ine.tourism.type.category"
    _description = "Hotel category in the Ministry of Tourism. Used for INE statistics."

    type = fields.Char(required=True)
    category = fields.Char(required=True)
    survey_type = fields.Selection(
        selection=[
            ("hotel", "Hotel Occupancy Survey (EOH)"),
            ("apartments", "Tourist Apartments Occupancy Survey (EOAP)"),
        ],
        default="hotel",
        required=True,
        help="INE occupancy survey this category belongs to. It determines "
        "the XML questionnaire format generated by the INE wizard.",
    )

    def name_get(self):
        data = []
        for record in self:
            display_value = record.category + " (" + record.type + ") "
            data.append((record.id, display_value))
        return data
