from . import (
    backend_guesty,
    pms_property,
    pms_reservation,
    pms_property_reservation,
    pms_guesty_calendar,
    pms_configurator,
    product,
    res_company,
    res_config_settings,
    res_partner_guesty,
    res_partner,
    sale_order,
    sale_order_line,
    payment_transaction,
    crm_lead,
    crm_lead_rule,
)
