from . import wizard_split_join_swap_reservation
from . import wizard_massive_changes
from . import wizard_advanced_filters
from . import pms_booking_engine
from . import folio_make_invoice_advance
from . import wizard_payment_folio
from . import wizard_folio_changes
from . import wizard_several_partners
from . import pms_booking_duplicate
from . import folio_payment_link
