[project]
name = "odoo-addons-oca-pms"
version = "19.0.20260706.0"
dependencies = [
    "odoo-addon-pms_account==19.0.*",
    "odoo-addon-pms_account_asset==19.0.*",
    "odoo-addon-pms_base==19.0.*",
    "odoo-addon-pms_contract==19.0.*",
    "odoo-addon-pms_crm==19.0.*",
    "odoo-addon-pms_project==19.0.*",
    "odoo-addon-pms_purchase==19.0.*",
    "odoo-addon-pms_sale==19.0.*",
    "odoo-addon-pms_stock==19.0.*",
    "odoo-addon-pms_website==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
